version: '3.9'
services:
  node:
    image: node:18
    volumes:
      - ./app:/app
    working_dir: /app
    command: node src/index.js
    restart: always

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    restart: always
